Install node and build a distillery release

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
-if [ -f $1/mix.exs ]; then
+if [ -f "$1/mix.exs" ]; then
+  if [ ! -f "$1/rel/config.exs" ]; then
+    echo "Found mix.exs, but could not find rel/config.exs. Install and configure distillery to use this buildpack."
+    echo "https://hexdocs.pm/distillery/introduction/installation.html"
+    exit 1
+  fi
+
   echo Elixir
   exit 0
 else
